### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by Hastws** [xinjie-liu/AutoEncodingBayesianInverseGames.jl#1]
ERROR: MethodError: no method matching ParametricMCPs.ParametricMCP(::MCPGameSolver.var"#38#54"{…}, ::ParametricMCPs.SparseFunction{…}, ::ParametricMCPs.SparseFunction{…}, ::Vector{…}, ::Vector{…}, ::Int64)
The type `ParametricMCPs.ParametricMCP` exists, but no method is defined for this combination of argument types when trying to construct it.

Closest candidates are:
  ParametricMCPs.ParametricMCP(::T1, ::T2, ::T3, ::Vector{Float64}, ::Vector{Float64}, ::Int64, ::Int64) where {T1, T2, T3}
   @ ParametricMCPs ~/.julia/packages/ParametricMCPs/VeFUh/src/parametric_problem.jl:7
  ParametricMCPs.ParametricMCP(::Any, ::Any, ::Any, ::Any; backend, problem_size, kwargs...)
   @ ParametricMCPs ~/.julia/packages/ParametricMCPs/VeFUh/src/parametric_problem.jl:53
  ParametricMCPs.ParametricMCP(::Vector{T}, ::Vector{T}, ::Vector{T}, ::Vector, ::Vector; compute_sensitivities, warm_up_callbacks, parallel, backend_options) where T<:Union{FastDifferentiation.Node, Symbolics.Num}
   @ ParametricMCPs ~/.julia/packages/ParametricMCPs/VeFUh/src/parametric_problem.jl:74

Stacktrace:
 [1] MCPGameSolver.MCPGame(game::TrajectoryGamesBase.TrajectoryGame{…}, horizon::Int64, context_state_block_dimensions::Vector{…})
   @ MCPGameSolver ~/projects/AutoEncodingBayesianInverseGames.jl/lib/MCPGameSolver/src/problem_formulation.jl:214
 [2] MCPGameSolver.MCPCoupledOptimizationSolver(game::TrajectoryGamesBase.TrajectoryGame{…}, horizon::Int64, context_state_block_dimensions::Vector{…})
   @ MCPGameSolver ~/projects/AutoEncodingBayesianInverseGames.jl/lib/MCPGameSolver/src/problem_formulation.jl:227
 [3] macro expansion
   @ ./some.jl:158 [inlined]
 [4] run_intersection_inference(; number_trials::Int64, solver::Nothing, num_player::Int64, ego_agent_id::Int64, lane_id_per_player::Vector{…}, ll::Float64, lw::Float64, turn_radius::Float64, collision_radius::Float64, max_velocity::Float64, max_acceleration::Float64, max_ϕ::Float64, collision_avoidance_coefficient::Int64, hard_constraints::Bool, rng::Random.MersenneTwister, horizon::Int64, n_sim_steps::Int64, vector_size::Int64, turn_length::Int64, max_grad_steps::Int64, lr::Float64, root_folder::String, save::Bool, training_dataset_size::Int64, episode_slicing_interval::Int64)
   @ DrivingExample ~/projects/AutoEncodingBayesianInverseGames.jl/src/simulation_script/intersection_inference.jl:48
 [5] run_intersection_inference()
   @ DrivingExample ~/projects/AutoEncodingBayesianInverseGames.jl/src/simulation_script/intersection_inference.jl:9
 [6] top-level scope
   @ REPL[3]:1
Some type information was truncated. Use `show(err)` to see complete types.

how to solve this, Master

**Comment by xinjie-liu** [comment]
Hi there, could you give a minimum example to reproduce this error? I will look into it.

**Comment by Hastws** [comment]
![Screenshot from 2024-10-23 17-54-21](https://github.com/user-attachments/assets/4a75c2da-b7a3-488b-a3e2-b83c3c5f24da)

**Comment by xinjie-liu** [comment]
Hi, thanks for following up! It is a bit hard to see the problem without seeing the exact versions of Julia and the packages you're using. I just tried running the code; it was running fine for my setup. But I do think I have encountered this error once before. I think the problem is that this package has not been maintained for the newer version of `ParametricMCPs` yet. Therefore, at this point, could you try running using Julia 1.10.5 + the exact versions of the packages shown in the project files? This can be done by following the "Initial setup" section in the README. 

I also just uploaded pretrained model, if you follow the steps exactly, you should be able to run examples with the pretrained model. Let me know if you have any further questions. Thanks!
